spring:
  application:
    name: Aurora Appliation
  datasource:
    url: jdbc:mysql://localhost:3306/aurora?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
security:
  basic:
    enabled: false

#prod
---
spring:
  profiles:
    active: prod
  datasource:
    username: root
    password: minis-production
  output:
    ansi:
      enabled: never
server:
  port: 7000

#test
---
spring:
  profiles:
    active: test
  datasource:
      username: root
      password:
  thymeleaf:
      cache: false
  jpa:
    hibernate:
      ddl-auto: create-drop
  output:
      ansi:
        enabled: always
server:
  port: 8080

#dev
---
spring:
  profiles:
    active: dev
  datasource:
      username: root
      password:
  thymeleaf:
    cache: false
server:
  port: 8080
assets:
  path: //127.0.0.1:8900